set(HEADER_PARSER headerParser)
add_executable(
	${HEADER_PARSER}
	src/headerParser.c
	)
target_sources(${HEADER_PARSER} PRIVATE
	${HEADER_PARSER_SRC}
	)

set(LIB_NAME headerparser)

set(HEADER_PARSER_SH ${HEADER_PARSER}_sh)
add_library(${HEADER_PARSER_SH} SHARED ${HEADER_PARSER_LIB_FILES})
#set_target_properties(${HEADER_PARSER_SH} PROPERTIES VERSION ${PROJECT_VERSION})
set_target_properties(${HEADER_PARSER_SH} PROPERTIES OUTPUT_NAME ${LIB_NAME})
set_target_properties(${HEADER_PARSER_SH} PROPERTIES POSITION_INDEPENDENT_CODE ON)

set(HEADER_PARSER_ST ${HEADER_PARSER}_st)
add_library(${HEADER_PARSER_ST} STATIC ${HEADER_PARSER_LIB_FILES})
#set_target_properties(${STATIC_LIB} PROPERTIES VERSION ${PROJECT_VERSION})
##set_target_properties(${STATIC_LIB} PROPERTIES PUBLIC_HEADER include/utils/)
set_target_properties(${HEADER_PARSER_ST} PROPERTIES OUTPUT_NAME ${LIB_NAME})
set_target_properties(${HEADER_PARSER_ST} PROPERTIES POSITION_INDEPENDENT_CODE ON)
