#ifndef HEADER_PARSER_STRING_POOL_H
#define HEADER_PARSER_STRING_POOL_H

#define ENDIAN_NAMES_SIZE (3)
static const char* endian_type_names[ENDIAN_NAMES_SIZE] = {
    "unsupported",
    "little",
    "big"
};

#define HEADER_TYPES_SIZE (17)
static const char* header_type_names[HEADER_TYPES_SIZE] = {
    "unsupported",
    "APK",
    "ART",
    "CFBFF", // Compound File Binary Format
    "MS-DOS",
    "PE",
    "NE",
    "VxD",
    "OS/2-2.0",
    "DEX",
    "ELF",
    "Mach-O",
    "MSI",
    "JAR-Archive",
    "Java-Class",
    "Word-DocX",
    "ZIP-Archive",
};

#define ARCHITECTURE_NAMES_SIZE (100)
static const char* architecture_names[ARCHITECTURE_NAMES_SIZE] = {
    "unsupported",
    "Alpha",
    "Alphamosaic",
    "Advanced-Logic-Corp",
    "Altera",
    "Altium",
    "AMD",
    "Andes",
    "Android",
    "Arc",
    "Arca",
    "Arm",
    "Atmel",
    "AT&T",
    "Axis-Communications",
    "Beyond",
    "Blackfin",
    "Bluechip",
    "Broadcom",
    "CloudShield",
    "Cracy",
    "CSMP",
    "CSR",
    "Cyan",
    "Cypress",
    "CEE",
    "CEF",
    "NVIDIA-CUDA",
    "Dallas",
    "Digital-Equipment-Corp",
    "Denso",
    "DVAX", // DEC
    ".Net",
    "EFI-Byte-Code",
    "Element",
    "Epson",
    "eXcess",
    "Freescale",
    "FTDI",
    "Fujitsu",
    "Hitachi",
    "Harvard-University-MIOF",
    "IBM",
    "Icera",
    "Infineon",
    "Intel",
    "Imagination",
    "Java",
    "KIPO-KAIST",
    "Donald-Knuth",
    "KM",
    "Lattice",
    "LSI",
    "Nano-Radio",
    "NJR",
    "National-Semiconductor",
    "NXP",
    "MAX",
    "Matsushita",
    "MCST",
    "Mips",
    "Mitsubishi",
    "Motorola",
    "M68k",
    "M88k",
    "Moxie",
    "Microchip-Technology",
    "NEC",
    "OsX",
    "PA-RISC",
    "Paneve",
    "picoJava",
    "PKU",
    "PPC",
    "QUALCOMM",
    "Renesas",
    "RISC",
    "OpenRISC",
    "RISC-V",
    "Silicon-Graphics",
    "Sharp",
    "Siemens",
    "SiTera",
    "Sony",
    "SPARC",
    "STMicroelectronics",
    "Sunplus",
    "Tenor-Network",
    "Tensilica",
    "Thompson",
    "Texas-Instruments",
    "Tilera",
    "Toyota",
    "Trebia",
    "TRW",
    "Ubicom",
    "Visum",
    "Xilinx",
    "XMOS",
    "Zilog",
};

#endif
